apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresnew-pv
spec:
  storageClassName: manual
  capacity:
    storage: 100M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/twitter-pv0003/"
