apiVersion: v1
kind: Service
metadata:
  name: digest-service
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app: digest   
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: digest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: digest
  template:
    metadata:
      labels:
        app: digest
    spec:
      containers:
      - name: digest
        image:  matthewkoton/digest
        ports:
        - containerPort: 8081
        env:
        - name: POSTGRES_PASSWORD
          value: postgrespassword
        - name: POSTGRES_DB
          value: "twitty" 
        - name: POSTGRES_USER
          value: postgresuser
        - name: PGDATA
          value: /var/lib/postgresql/data/twitty
