apiVersion: v1
kind: Service
metadata:
  name: digest-service
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app: digest   
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: digest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: digest
  template:
    metadata:
      labels:
        app: digest
    spec:
      containers:
      - name: digest
        image:  yungmannofar/data_digest
        ports:
        - containerPort: 8081
        env:
        - name: POSTGRES_PASSWORD
          value: postgrespassword
        - name: POSTGRES_DB
          value: postgres 
        - name: POSTGRES_USER
          value: postgresuser
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: postgres-config  
              key: url