apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret-config
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXN1c2Vy #echo -n "postgresuser" | base64
  POSTGRES_PASSWORD: cG9zdGdyZXNwYXNzd29yZA== #echo -n "postgrespassword" | base64
  POSTGRES_DB: cG9zdGdyZXM= #echo -n "postgres" | base64