# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: postgres-pv-claim
# spec:
#   storageClassName: manual
#   accessModes:
#   - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: postgres-pv-volume
# spec:
#   storageClassName: manual
#   capacity:
#     storage: 5Gi
#   accessModes:
#   - ReadWriteOnce
#   hostPath:
#     path: "/mnt/data"
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: postgres-secret-config
# type: Opaque
# data:
#   POSTGRES_USER: cG9zdGdyZXN1c2Vy #echo -n "postgresuser" | base64
#   POSTGRES_PASSWORD: cG9zdGdyZXNwYXNzd29yZA== #echo -n "postgrespassword" | base64
#   POSTGRES_DB: cG9zdGdyZXM= #echo -n "postgres" | base64
# ---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config  
data:
  url: postgres-service
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 5432
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: yungmannofar/database #postgres:latest
        ports:
        - containerPort: 5432
          name: postgres
        resources:
          limits:
            memory: 200Mi
            cpu: 500m
          requests:
            memory: 100Mi
            cpu: 200m
        env:
        - name: POSTGRES_PASSWORD
          value: postgrespassword
        - name: POSTGRES_DB
          value: postgres 
        - name: POSTGRES_USER
          value: postgresuser
        - name: PGDATA
          value: /var/lib/postgresql/data/twitty
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-pv-claim
      volumes:
      - name: postgres-pv-claim
        persistentVolumeClaim:
          claimName: postgres-pv-claim      

