apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: yungmannofar/database #postgres:latest
        ports:
        - containerPort: 5432
          name: postgres
        resources:
          limits:
            memory: 200Mi
            cpu: 500m
          requests:
            memory: 100Mi
            cpu: 200m
        env:
        - name: POSTGRES_PASSWORD
          value: postgrespassword
        - name: POSTGRES_DB
          value: twitty 
        - name: POSTGRES_USER
          value: postgresuser
      #   - name: PGDATA
      #     value: /var/lib/postgresql/data/twitty
      #   volumeMounts:
      #   - mountPath: /var/lib/postgresql/data
      #     name: postgres-pv-claim
      # volumes:
      # - name: postgres-pv-claim
      #   persistentVolumeClaim:
      #     claimName: postgres-pv-claim    

