# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: postgres-twitter-pv
# spec:
#   storageClassName: manual
#   capacity:
#     storage: 100M
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: "/data/twitter-pv0001/"
# ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # labels:
  #   app: postgres
  name: postgres-pv-claim
  # namespace: twitty 
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100M